### ISSUE TITLE
2.1.5, split up password and certificate based authentication

### ISSUE THREAD

**Issue by roelstorms** [OWASP/IoT-Security-Verification-Standard-ISVS#35]
Does it make sense to split up requirement 2.1.5: 

Verify certificate based authentication is preferred over password based authentication within the IoT ecosystem.

"Use password authentication using strong passwords" could be a L1
"Use certificate based authentication" could be L3

Is there a recommendation on certificate based authentication?
Unique certificate per device/user?
How are these certificates best generated and installed on the device? During manufacturing, registration, something else?
For professional IoT devices, the manufacturer might want to support protocols such as SCEP for certificate mgmt.
Any requirements regarding certificate renewal?

Maybe all of this is going in to much detail.

In IoT there are sometimes webservers which are built into devices. The HTTPS certificate can sometimes be retrieved. If that certificate is signed by a public CA for a domain owned and operated by the company, this certificate can be misused in MitM or phishing attacks.

**Comment by cbassem** [comment]
Hi Roel, thank you for your feedback! This is much appreciated. Please find my feedback below. 

- Concerning the use of passwords/certificates. If we split up 2.1.5, then we would hint towards using passwords, which is something we would like to avoid. Use of strong passwords is covered in 2.1.3 and 2.1.6. Perhaps we should add the requirement that passwords should be "strong" to 2.1.6. I notice that this one is perhaps not covered explicitly enough. 

- Concerning certificate based authentication. 2.4.1 discusses that cryptographic secrets should be unique per device. Are there other recommendations concerning certificate based authentication that you're thinking about? 

- How are these certificates best generated and installed on the device? I feel like there is not "one" true way on how to tackle this. This can be done both during manufacturing or during registration/enrolment of the device, you can even have the user upload the client certificate themselves. Some general things that I think of are: the certificate should be generated securely, transferred securely and stored securely. How this is done, feels implementation specific and perhaps too much detail for the ISVS.

- Concerning certificate renewal, this is tackled to a certain extend in the Software Updates section in V3.

- Concerning certificates being retrieved, I feel this is covered by the data protection section in V2 and by 2.4.4 in Cryptography.

**Comment by roelstorms** [comment]
Thanks for clarifying. 2.1.5 could then simply be: Use certificate based authentication instead of password based authentication.

The term “prefer” makes the requirement a bit ambiguous.

 

On the other points, I agree that a certain level of detail needs to be chosen for the entire set of requirements.

 

On you last point, I didn’t mean certificates to be used for client side authentication but rather server certificates with a CN and SAN of the vendors corporation. I would add that it is not just about protecting the certificate but simply not using a publicly signed certificate which is trusted for one of your corporate domains.

What I am looking for is a requirement that prevents this: https://gist.github.com/nstarke/a611a19aab433555e91c656fe1f030a9

Again, this might be to granular for this set of requirements.

**Comment by scriptingxss** [comment]
Maybe we should differentiate user authentication and M2M in terms of certificates and passwords? Users will often opt for UN/PW while M2M implementation are different in terms of managing credential lifecycles. We will keep thinking about this one and suggested revisions.

**Comment by roelstorms** [comment]
Indeed, I mixed two different applications of certificates. But your consideration makes sense.

**Comment by cetome** [comment]
I would suggest to add API keys in the description: they are effectively "passwords".
The developer shall ensure that API keys remain secret (such as not stored in the source code) and are not shared between devices.

**Comment by cbassem** [comment]
Closed because this should now be covered by PR #64. Split up the authentication requirements in a more requirements.
