### ISSUE TITLE
V4 Communication Requirements bullet point limited to BT and Wi-Fi

### ISSUE THREAD

**Issue by scradster** [OWASP/IoT-Security-Verification-Standard-ISVS#46]
https://github.com/OWASP/IoT-Security-Verification-Standard-ISVS/blob/cabb80a5f4c80b80cf77b08a73f197965f673e48/en/V4-Communication_Requirements.md#L11

What about ZigBee for example?  Could be resolved with

`Use the strongest security settings available for wireless communication`

But IMHO also wired communication should be protected as good as possible, so my suggestion is this:

`Use the strongest security settings available for any communication protocol in use.`

**Comment by scriptingxss** [comment]
Agreed! How about the following?

`Use the strongest security settings available for wired and wireless communication protocols.`

**Comment by scriptingxss** [comment]
@scradster would you mind submitting a pull request for this?
