### ISSUE TITLE
4.1.3 doesn't specify what extensions of the certificate should be verified

### ISSUE THREAD

**Issue by scradster** [OWASP/IoT-Security-Verification-Standard-ISVS#47]
https://github.com/OWASP/IoT-Security-Verification-Standard-ISVS/blame/ede47af57ec0d7faaf41261d2547ef3e97dc3ffa/en/V4-Communication_Requirements.md#L21

Leaned on 4.1.6 for L2/3 I suggest to rephrase this requirement as follows for L1:

`Verify that in case TLS is used, the device checks the validity of endpoint certificates and disallows connections to endpoints that use an invalid certificate (e.g. wrong common name, untrusted issuer, etc).`

**Comment by cbassem** [comment]
Agreed, there are more properties to validate than the certificate's signature. how about the following?

`Verify that in case TLS is used, the device verifies the validity of endpoint certificates and disallows connections to endpoints that use an invalid certificate (e.g. invalid signature, wrong common name, untrusted issuer, etc).`

**Comment by cbassem** [comment]
Applied changes in commit 0431716
