### ISSUE TITLE
4.3.5 Reference to AES key size unclear

### ISSUE THREAD

**Issue by scradster** [OWASP/IoT-Security-Verification-Standard-ISVS#50]
https://github.com/OWASP/IoT-Security-Verification-Standard-ISVS/blame/4582968e2b0323a02cfba36b9d32584d4eb0489a/en/V4-Communication_Requirements.md#L43

Maybe it's me, but I don't get the point of the reference to the 16-32 byte AES key sizes. Why not just require this:

`Verify that encryption keys are the maximum size the device supports and that this size is sufficient to adequately protect the information transmitted over the Bluetooth connection.`

**Comment by cbassem** [comment]
The 16-32 bytes are the key sizes of respectively AES-128 and AES-256. The second part of the requirement was meant as a warning that you might find yourself using a smaller key size if you're not careful. The proposed rewording makes a lot of sense.

**Comment by cbassem** [comment]
Applied changes in commit 45e13ed.
