### ISSUE TITLE
V5 HW Requirements clarification

### ISSUE THREAD

**Issue by scradster** [OWASP/IoT-Security-Verification-Standard-ISVS#51]
https://github.com/OWASP/IoT-Security-Verification-Standard-ISVS/blame/4582968e2b0323a02cfba36b9d32584d4eb0489a/en/V5-Hardware_Platform_Requirements.md#L5

The second sentence in the objective seems very important to me and could be extended like follows to make the point even clearer to the reader.

`On the other hand, hardware that contains backdoors or undocumented debug features can completely compromise the security of the entire device even if adequate security measures have been taken on the other layers of the stack.`

**Comment by scriptingxss** [comment]
Sure, hows the following?

`Hardware is more difficult and costly to compromise and subvert than software. Therefore hardware security can provide a robust foundation for embedded device security. On the other hand, hardware that contains backdoors or undocumented debug features can completely compromise the security of the entire device even if adequate security measures have been taken on the other layers of the stack.`

**Comment by scriptingxss** [comment]
@scradster would you mind submitting a pull request for this?
