### ISSUE TITLE
1.2.3. Security-by-default

### ISSUE THREAD

**Issue by cetome** [OWASP/IoT-Security-Verification-Standard-ISVS#67]
I would enhance the suggestion to push for secure by default configuration at release as follows:
Verify the device is released with firmware and configuration appropriate for a release build (as opposed to debug versions), **with appropriate security functions enabled by default**.

The appropriate security functions would refer to the threat model done in 1.1.

**Comment by scriptingxss** [comment]
How about one of the following? 

`Verify the device is released with secure firmware default configurations appropriate for a release build (as opposed to debug versions).`

or 
`Verify the device is released with firmware configured with secure defaults appropriate for a release build (as opposed to debug versions).`

Secure defaults and security functions are somewhat ambiguous in terms of requirements. It's not uncommon for product program managers or software leads to brush over these types of terms based on their (lack of) understanding.

**Comment by cetome** [comment]
I really like the second one:
`Verify the device is released with firmware configured with secure defaults appropriate for a release build (as opposed to debug versions).`

**Comment by scriptingxss** [comment]
When you have a chance, please submit a PR with the following 
`Verify the device is released with firmware configured with secure defaults appropriate for a release build (as opposed to debug versions).`

**Comment by scriptingxss** [comment]
Added
