### ISSUE TITLE
Create 1.2.10 Secure update provisions

### ISSUE THREAD

**Issue by cetome** [OWASP/IoT-Security-Verification-Standard-ISVS#70]
Verify that all components can be updated

Additionally: verify that all components are supported by their supplier for a duration at least equivalent to the product warranty period.

**Comment by scriptingxss** [comment]
This is a great suggestion and one that I'm battling myself :) 

1.2.9 - How does the following sound?
 
`Verify that all components including semiconductor drivers, SDKs, and modules (5G, LTE, Bluetooth, Wi-Fi, ZigBee) can be updated to provide security patches in alignment with the product's support or end-of-life policy.`

**Comment by scriptingxss** [comment]
Added
