### ISSUE TITLE
2.x Configuration backup

### ISSUE THREAD

**Issue by cetome** [OWASP/IoT-Security-Verification-Standard-ISVS#71]
There is not option regarding the backup of configuration, which could support resilience requirements.

Would it make sense to add a requirement: "allow users to backup their configuration"? L1 to L3.

**Comment by scriptingxss** [comment]
This may be more a feature requirement. 3.4.5 captures retaining configs through updates which have more security impact. 

We plan to add a resilience chapter in future revisions which covers tamper and reverse engineering similar to MASVS. We can revisit additional requirements then.
