### ISSUE TITLE
2.1.16 is confusing

### ISSUE THREAD

**Issue by cetome** [OWASP/IoT-Security-Verification-Standard-ISVS#72]
Confusing wording "Verify good password policies are enforced throughout the IoT ecosystem by disallowing hardcoded passwords **and provisioning duplicate identities or passwords across devices.**" => I Would recommend: "and provisioning unique identities and passwords for each device."

**Comment by scriptingxss** [comment]
I agree. We will be removing 2.1.6 and updating with more concise password practices in PR #64. Stay tuned!
