### ISSUE TITLE
3.4.12. Secure communications

### ISSUE THREAD

**Issue by cetome** [OWASP/IoT-Security-Verification-Standard-ISVS#74]
I can't find any requirement about the communication channel for secure updates.
Suggestion to add "3.4.12 Verify that over the air updates are transmitted using a secure communication channel"

**Comment by scriptingxss** [comment]
I think you are right 😅. 4.1.1 is a catch all for secure communications in an IoT ecosystem although we do want to be explicit when discussing updates. 

Revised requirement below:
`Verify that software and firmware updates are transmitted using an encrypted communication channel.`

The control objective for this section could also use a sentence or two around software updates. Would you be open to writing one up and sending a PR? 😄 

cc: @cbassem in case I overlooked something.

**Comment by cetome** [comment]
Done :) Please review and amend as necessary.

**Comment by scriptingxss** [comment]
The PR does not allow edits by maintainers. Let's go with 7baf4a8

**Comment by scriptingxss** [comment]
Mergeed
