### ISSUE TITLE
3.4.13. Authorization to update

### ISSUE THREAD

**Issue by cetome** [OWASP/IoT-Security-Verification-Standard-ISVS#75]
A main issue comes from insecure updates being flashed without authorization (think ransomware or Botnet script).
A good way to protect from this is to have the following requirement: **Verify that updates can only be installed by authorized users.**

**Comment by scriptingxss** [comment]
Secure / trusted boot, using an MAC LSM (i.e.SELinux), running in a containerized architecture, or integrity measurement implementations would cover this even if malware tried to load code at runtime.
