### ISSUE TITLE
4.1.2: Align recommendation on TLS with ASVS

### ISSUE THREAD

**Issue by maximbaele** [OWASP/IoT-Security-Verification-Standard-ISVS#90]
Regarding: "4.1.2 Verify that in case TLS is used its configured to only use FIPS-compliant cipher suites (or equivalent)."

In my opinion, FIPS compliant ciphers are aimed at government and defense applications, and more modern but still widely accepted ciphers can provide better performance
I believe this is better put in the ASVS: "9.1.2 Verify using up to date TLS testing tools that only strong cipher suites are
enabled, with the strongest cipher suites set as preferred."

Would love to know if there is a specific reasoning behind the FIPS recommendation or hear what others have to say

**Comment by scriptingxss** [comment]
Agreed, the proposed language is better put and more interoperable. There wasn't specific reasoning behind the language other than aligning with known standards. Thank you for the MR.
